# Site settings
title: Turn Over
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.turn-over.be" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 4
# Build settings
markdown: kramdown
exclude: [node_modules]
